// import type { Metadata } from "next";
// import { ClerkProvider, SignedIn, SignedOut, SignInButton, UserButton } from "@clerk/nextjs";
// import "./globals.css";
// import { Inter, Roboto } from "next/font/google";
// import Header from '@/app/components/header'
// import Footer from '@/app/components/footer'

// const inter = Inter({ subsets: ["latin"] });
// const roboto = Roboto({ subsets: ["latin"], weight: ["400", "700"] });


// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <ClerkProvider>
//       <html lang="en">
//         <header>
//           <SignedOut>
//             <SignInButton />
//           </SignedOut>
//           <SignedIn>
//             <UserButton />
//           </SignedIn>
//         </header>
//         <body className='className={`${inter.className} ${roboto.className} max-w-[1440px] mx-auto'>
//           <Header />
//           {children}
//           <Footer />
//         </body>
//       </html>
//     </ClerkProvider>
//   );
// }



import type { Metadata } from "next";
import { ClerkProvider, SignedIn, SignedOut, SignInButton, UserButton } from "@clerk/nextjs";
import "./globals.css";
import { Inter, Roboto } from "next/font/google";
import Header from "@/app/components/header";
import Footer from "@/app/components/footer";
import Link from "next/link";
import Image from 'next/image'

const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${inter.className} ${roboto.className} max-w-[1440px] mx-auto`}>
          <Header />
          <main>{children}</main>
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}
